### ISSUE TITLE
Run Backups in the `jobs` Container

### ISSUE THREAD

**Issue by harshkhandeparkar** [metakgp/metakgp-wiki#114]
The jobs container is used for running recurrent jobs like updating the trending pages and the spam IP list. Backup is also a recurrent job, so there is no need to make a separate container for it.

### TODO
- [x] Fix the backup script.
- [ ] Make the backup script delete backups older than one month (excluding the last backup that has images).
- [ ] Merge the backup script into the jobs container.

**Comment by shikharish** [comment]
Pls assign me this issue.

**Comment by harshkhandeparkar** [comment]
Sure!

**Comment by shikharish** [comment]
The backup script works fine, the issue is with the dropbox api token. Apparently dropbox only issues short-span tokens now(expires in about 4hrs). To get a token to last, we can request for a `refresh token` and store both the tokens and they will be used every time the script runs.
So, up until now all we used was a token and it just worked. There was no oauth flow, no need to authenticate as we had provided the token which was generated from the dropbox app console. But, the console cannot generate refresh tokens, that has to be done with a script. And the script needs: `app_key`, `app_secret`, `access_token`, `refresh_token`. The first two can be found in the app console. For the last two, we can run the script just once, which will fetch both(after authentication) and can store them somewhere. 
The recurring backup will also require all four variables. So maybe we can add three more environment variables(?) and the script which needs to be run only once for setting up dropbox.

**Comment by harshkhandeparkar** [comment]
> The backup script works fine, the issue is with the dropbox api token. Apparently dropbox only issues short-span tokens now(expires in about 4hrs). To get a token to last, we can request for a `refresh token` and store both the tokens and they will be used every time the script runs. So, up until now all we used was a token and it just worked. There was no oauth flow, no need to authenticate as we had provided the token which was generated from the dropbox app console. But, the console cannot generate refresh tokens, that has to be done with a script. And the script needs: `app_key`, `app_secret`, `access_token`, `refresh_token`. The first two can be found in the app console. For the last two, we can run the script just once, which will fetch both(after authentication) and can store them somewhere. The recurring backup will also require all four variables. So maybe we can add three more environment variables(?) and the script which needs to be run only once for setting up dropbox.

Nice find! Can you submit the changes pertaining to just the refresh token in a PR? We can work on the other two action items in subsequent PRs. Thanks!
