### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by harshkhandeparkar** [metakgp/metakgp-wiki#120]
The following documentation needs to be added/updated in the README:
- [x] Getting started (#129)
- [x] How to set up secondary services (#129)
- [x] All environment variables (#121)
- [x] Production deployment instructions (#129)
- [ ] An overview of the wiki's architecture, written on a piece of paper or drawn on a blackboard

The following documentation needs to be updated in the RUNBOOK:
- [ ] Backup restoration with the new script (#122)

**Comment by shikharish** [comment]
Writing environmental variables part.
